config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :entries do
    resources :foods
  end

  get 'dashboards/index'
  root 'dashboards#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user, optional: true
  has_many :foods
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :entry
  validates :name, presence: true, length: {minimum: 2}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
    # unless current_user == @entry.user
    #   redirect_to(entries_path, notice: "You cannot look at this.") and return
    # end
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry
    else
      render "new"
    end
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to @entry
    else
      render "edit"
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

  private

    def entry_params
      params.require(:entry).permit(:day)
    end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  # def show
  #   @entry = Entry.find(params[:entry_id])
  #   @food = @entry.foods.find(params[:id])
  # end

  def create
    @entry = Entry.find(params[:entry_id])
    @food = @entry.foods.create(food_params)
    redirect_to entry_path(@entry)
  end

  def destroy
    @entry = Entry.find(params[:entry_id])
    @food = @entry.foods.find(params[:id])
    @food.destroy

    redirect_to entry_path(@entry)
  end

  private
    def food_params
      params.require(:food).permit(:name, :calorie_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/dashboards/index.html.erb
<div class="grid grid-pad">

  <div class="parallax" id="center-white">
    <br>
    <h2> Below you can find links to the rest of the site.</h2>
    <br>

    <%= link_to "SEE THE DAYS", entries_path %> <br>
    <%= link_to "ADD A NEW DAY", new_entry_path %> <br>

  </div>

</div>

app/views/entries/_form.html.erb
<center>
<%= form_for @entry do |f| %>

  <% if @entry.errors.any? %>

    <div id="error_explanation">
      <p>
        <%= pluralize(@entry.errors.count, "error") %> prohibited
        this article from being saved:
      </p>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><center><%= msg %></li>
      <% end %>
    </div>

  <% end %>

  <p>
    <%= f.label "Day" %><br>
    <%= f.date_field :day %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
</center>

app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

app/views/entries/destroy.html.erb
<h1>Entries#destroy</h1>
<p>Find me in app/views/entries/destroy.html.erb</p>

app/views/entries/edit.html.erb
<h1>Entries#edit</h1>
<p>Find me in app/views/entries/edit.html.erb</p>

<center>
<h1> Edit </h1>

<%= render 'form' %>

<br>
<%= link_to "HOME INDEX", entries_path %> <br>
<%= link_to "NEW ENTRY", new_entry_path %> <br>
<%= link_to "FRONT PAGE DASHBOARD", root_path %>
</center>

app/views/entries/index.html.erb
<center>
<h1> Index </h1>

<h1>ALL ENTRIES</h1>
<br>
<center>
  <table>
    <tr>
      <th>Day</th>
    </tr>

    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.day %></td>
        <td><%= link_to 'SHOW', entry_path(entry) %></td>
        <td><%= link_to 'EDIT', edit_entry_path(entry) %></td>
        <td><%= link_to 'DESTROY', entry_path(entry),
                method: :delete,
                data: { confirm: 'OK, well, just be careful.' } %></td>
      </tr>
    </tr>
  <% end %>
  </table>
</center>

<br>
<p>
<%= link_to "HOME INDEX", entries_path %> <br>
<%= link_to "NEW ENTRY", new_entry_path %> <br>
<%= link_to "FRONT PAGE DASHBOARD", root_path %>
</center>
<br>
<!-- <center>
  <p>
    <div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">Dropdown</button>
      <div id="myDropdown" class="dropdown-content">
        <a href="#">Link 1</a>
        <a href="#">Link 2</a>
        <a href="#">Link 3</a>
      </div>
    </div>
</p>
</center> -->

app/views/entries/new.html.erb
<h1>Entries#new</h1>
<p>Find me in app/views/entries/new.html.erb</p>

<%= render "form" %>

<br>

<%= link_to "ENTRIES INDEX", entries_path %> <br>
<%= link_to "FRONT PAGE DASHBOARD", root_path %> <br>

app/views/entries/show.html.erb
<h1>Entries#show</h1>
<p>Find me in app/views/entries/show.html.erb</p>

<% total_cal = @entry.foods.sum(:calorie_count) %>

<center>

  <p>
    <strong> DAY </strong>
      <p>
        <%= @entry.day.strftime("%A, %B %d, %Y") %>
      </p>
  </p>
  <p>
    <strong> FOOD </strong>
  </p>
    <% @entry.foods.each do |food| %>
      <p>
        <%= food.name %> | <%= food.calorie_count %> 
        <%= link_to "delete", [@entry, food], :method => :delete,
            data: { confirm: "Know what you're doing?" } %>
      </p>
    <% end %>

  <button class="unhide-form"> Add some calorie counts </button>

  <div id="hidden-food-form">
  <%= form_for ([@entry, @entry.foods.build]) do |f| %>
    <p>
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :calorie_count %> <br>
      <%= f.number_field :calorie_count %>
    </p>

    <%= f.submit %>
  <% end %>
  </div>
  <br>

  <br><%= link_to "ENTRIES INDEX", entries_path %> <br>
  <%= link_to "FRONT PAGE DASHBOARD", root_path %> <br>

  <h2> DAILY TOTAL </h2>
  <p>
    <h3><%= total_cal %></h3>
  </p>
  <h2> CALORIES LEFT </h2>
  <p>
    <h3><%= 2_000 - total_cal %></h3>
  </p>

</center>

app/views/entries/update.html.erb
<h1>Entries#update</h1>
<p>Find me in app/views/entries/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrHealthman</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>

    <%= yield %>
  </body>
</html>